Repository karthikrangasai/Deep-Learning-Deep-Learning, pull requests merged in 2020-10, with the labels that each got.

#3 Fix bugs in metrics used for training
  models/random_model_trainer.py
  script.py
Labels: bug, hacktoberfest-accepted

#4 Add provision to save models at any stage (before or after training)
  models/random_model_trainer.py
  script.py
Labels: enhancement, hacktoberfest-accepted

#5 Added ML models to compare performance with DL models
  README.md
  ml_script.py
  models/DT.png
  models/DT_confusion_matrix.png
  models/LogisticRegression.png
  models/LogisticRegression_confusion_matrix.png
  models/RandomForest.png
  models/RandomForest_confusion_matrix.png
  models/SVM.png
  models/SVM_confusion_matrix.png
Labels: documentation, enhancement
